version: '2'
services:
  api:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./:/var/www/html
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
